// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    IEpSearch: typeof import('~icons/ep/search')['default']
    PrivateMsgItem: typeof import('./components/message/PrivateMsgItem.vue')['default']
    PrivateMsgStatus: typeof import('./components/message/PrivateMsgStatus.vue')['default']
    PrivateSender: typeof import('./components/message/PrivateSender.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
